# Generated by Django 4.1.5 on 2023-01-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Secound Year'), ('3', 'Third Year'), ('4', 'Final Year maybe'), ('5', 'Why you here')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emails', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=100)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexscool.schools')),
            ],
        ),
        migrations.CreateModel(
            name='tclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=100, null=True)),
                ('enrolled', models.ManyToManyField(to='lexscool.students')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexscool.teachers')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexscool.teachers'),
        ),
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexscool.schools'),
        ),
        migrations.CreateModel(
            name='headmasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emails', models.EmailField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexscool.schools')),
            ],
        ),
    ]
