# Generated by Django 4.1.5 on 2023-01-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headmasters',
            old_name='emails',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='schools',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schools',
            name='tel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
