# Generated by Django 4.1.5 on 2023-01-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0002_rename_emails_headmasters_email_alter_schools_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='emails',
            new_name='email',
        ),
    ]
