# Generated by Django 4.1.5 on 2023-01-22 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0003_rename_emails_teachers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmasters',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexscool.schools'),
        ),
    ]
