# Generated by Django 4.1.5 on 2023-01-22 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0004_alter_headmasters_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmasters',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexscool.schools'),
        ),
    ]
