# Generated by Django 4.1.5 on 2023-01-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0005_alter_headmasters_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='advisor',
            new_name='teacher',
        ),
    ]
