# Generated by Django 4.1.5 on 2023-01-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0006_rename_advisor_students_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tclasses',
            old_name='descriptions',
            new_name='descript',
        ),
    ]
