# Generated by Django 4.1.5 on 2023-01-23 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0007_rename_descriptions_tclasses_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='tclasses',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexscool.schools'),
        ),
    ]
