# Generated by Django 4.1.5 on 2023-01-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0008_tclasses_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tclasses',
            old_name='enrolled',
            new_name='student',
        ),
    ]
