# Generated by Django 4.1.5 on 2023-01-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexscool', '0009_rename_enrolled_tclasses_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tclasses',
            old_name='descript',
            new_name='description',
        ),
    ]
